### ISSUE TITLE
how to use this in ubuntu server sqlsrv not working in linux thank you

### ISSUE THREAD

**Issue by hartjo** [ToNict/phalcon-sqlsrv#1]
how to use this in ubuntu server sqlsrv not working in linux thank you i have problem using this in ubuntu server but in windows working fine

**Comment by ruudboon** [comment]
I used FreeTDS + ODBC under FreeBSD to handle the driver part. I'm pretty sure it's also available on Linux.

**Comment by hartjo** [comment]
@ruudboon  yes thank you for reply i did used also freetds and odbc i will close this issue now thank you
