### ISSUE TITLE
Warn in Adapter

### ISSUE THREAD

**Issue by rmarinleal** [ToNict/phalcon-sqlsrv#2]
Hi,

I'm trying your library in linux, but I recive a warn in the Adapter Class.

In Adapter/Pdo/Sqlsrv.php
PDO::__construct() expects at most 4 parameters, 5 given in Adapter/Pdo/Sqlsrv.php line 345

Then I recive a message saying
Table 'xxx' doesn't exist in database when dumping meta-data for Xxx

I'm tried to launf statement directly in linw 345 changing the code by;
return parent::query($sqlStatement, $bindParams, $bindTypes);

but still dont work, I recive the message:
Trying to call method fetch on a non-object
#0 [internal function]: Phalcon\Db\Result\Pdo->numRows(Object(Phalcon\Db\Result\Pdo))

Thanks for your work ;)

**Comment by ruudboon** [comment]
What version of Phalcon are you running?
The ResultPdo extends the Phalcon pdo and looks like 5 parameters should be fine.
https://docs.phalconphp.com/en/latest/api/Phalcon_Db_Result_Pdo.html

**Comment by rmarinleal** [comment]
Hi!,

Now I understand my problem, in my project, many namespaces are overriden, so your class are using the native PHP PDO class instead of the phalcon, I've renamed the namespaces and now all works!!

I'm using the latest version of Phalcon 2.0.X

Thanks!
